ARG IMAGE=python
ARG IMAGE_TAG="3.14-alpine"
FROM ${IMAGE}:${IMAGE_TAG}
WORKDIR /tmp
COPY ./pyproject.toml ./
RUN pip install --upgrade pip && pip install . --break-system-packages
COPY *.py /tmp/
CMD ["pip", "list"]
